name: Build with CMake and Ninja

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup LLVM (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20210423/llvm-mingw-20210423-ucrt-ubuntu-18.04.tar.xz
          tar xf llvm-mingw-20210423-ucrt-ubuntu-18.04.tar.xz
          echo "$(pwd)/llvm-mingw-20210423-ucrt-ubuntu-18.04/bin" >> $GITHUB_PATH

      - name: Create Build Directory
        run: mkdir build

      - name: Run CMake
        run: |
          cd build
          cmake .. -GNinja

      - name: Run Ninja
        run: |
          cd build
          ninja

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-bin-${{ runner.os }}
          path: build/bin/
